version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=basic3tier
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    networks:
      - 3tier-network
    ports:
      - '5432:5432'
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=wayne@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - 'admindata:/var/lib/pgadmin'
    ports:
      - '5000:80'
    networks:
      - 3tier-network
  ui:
    build:
      context: ./ui
    restart: always
    ports:
      - '81:80'
    networks:
      - 3tier-network
  basic3tier-api:
    build:
      context: ./api
    restart: always
    ports:
      - '8080:80'
    networks:
      - 3tier-network
volumes:
  pgdata: null
  admindata: null
networks:
  3tier-network: null
